version: 2
jobs:
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths: node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Codecov
          command: npm run codecov
workflows:
  version: 2
  build:
    jobs:
      - test
